branch-protection:
  allow_disabled_policies: true  # TODO(fejta): remove, needed by k/website
  orgs:
    rawlingsj: 
      protect: true
      required_status_checks:
        contexts:
        - ci
        repos:
          spring-prow1:
            required_status_checks:
              strict: true
              contexts:
              - ci
          environment-dukepepper-production:
            required_status_checks:
              strict: true
              contexts:
              - promotion-gate
          environment-dukepepper-staging:
            required_status_checks:
              strict: true
              contexts:
              - promotion-gate

owners_dir_blacklist:
  default: null
  repos: null

prowjob_namespace: jx
pod_namespace: jx

push_gateway: {}

sinker:
  resync_period: 8m
  max_prowjob_age: 48h
  max_pod_age: 30m

tide:
  context_options:
    from-branch-protection: true
  skip-unknown-contexts:
    true
  queries:
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - rawlingsj/spring-prow1
    - rawlingsj/environment-dukepepper-staging
    - rawlingsj/environment-dukepepper-production
  target_url: https://tide.foo.bar.wine.io

