prowjob_namespace: jx
pod_namespace: jx

tide:
  context_options:
    from-branch-protection: true
  skip-unknown-contexts:
    true
  queries:
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - rawlingsj/spring-prow1

