
prowjob_namespace: jx
pod_namespace: jx

push_gateway: {}

sinker:
  resync_period: 55m
  max_prowjob_age: 48h
  max_pod_age: 30m

tide:
  context_options:
    from-branch-protection: true
  skip-unknown-contexts:
    true
  queries:
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - rawlingsj/spring-prow1
    - rawlingsj/environment-dukepepper-staging
    - rawlingsj/environment-dukepepper-production
  target_url: https://tide.foo.bar.wine.io

