triggers:
- repos:
  - rawlingsj/prow-dukepepper-jx-config

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins

plugins:
  rawlingsj/prow-dukepepper-jx-config:
  - config-updater
  - shrug
  - skip
  - yuks
  - size
  - dog
  - cat
  - heart